### ISSUE TITLE
2 formant query

### ISSUE THREAD

**Issue by agricolamz** [macleginn/vowel-classifier#1]
Works only with f1 - f2 - f3 query. Is it possible to query only f1 - f2?

**Comment by macleginn** [comment]
It works for me, what exact input did you use?

<img width="1019" alt="image" src="https://user-images.githubusercontent.com/4831042/35530289-4cabc6de-053c-11e8-8668-88c2258d4d0a.png">

**Comment by agricolamz** [comment]
Sorry, just 5 minutes ago didn't work... Sorry, now everything fine.

**Comment by agricolamz** [comment]
BTW, nice work!

**Comment by macleginn** [comment]
Most probably the issue was with the very slow first query (it's due to my using a free Heroku service). I added a notification on the subject.
